knpu_oauth2_client:
    clients:
        github:
            type: github
            client_id: '%env(GITHUB_ID)%'
            client_secret: '%env(GITHUB_SECRET)%'
            redirect_route: oauth_check
            redirect_params:
                service: github
        discord:
            type: discord
            client_id: '%env(DISCORD_ID)%'
            client_secret: '%env(DISCORD_SECRET)%'
            redirect_route: oauth_check
            redirect_params:
                service: discord