vich_uploader:
    db_driver: orm

    mappings:
        avatars:
            uri_prefix: '/uploads/avatars'
            upload_destination: '%kernel.project_dir%/public/uploads/avatars'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options:
                    property: id
